# Generated by Django 5.0.6 on 2024-06-17 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                ("project_context", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("rating", "Rating"),
                            ("free_response", "Free Response"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=255)),
                (
                    "data_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="myapp.datatable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datatable",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_tables",
                to="myapp.example",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_instructor", models.BooleanField(default=False)),
                ("points", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_context", models.TextField()),
                ("project_description", models.TextField()),
                ("provided_solution", models.TextField()),
                ("problem_type", models.CharField(default="Pl/SQL", max_length=255)),
                ("self_review", models.FloatField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("student_reviewed", models.BooleanField(default=False)),
                ("instr_reviewed", models.BooleanField(default=False)),
                ("no_student_reviews", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_problems",
                        to="myapp.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstrChecks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("problem_id", models.IntegerField()),
                ("student_id", models.IntegerField()),
                ("is_question", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("review_score", models.FloatField(default=0)),
                ("review", models.TextField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_checks",
                        to="myapp.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="example",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_examples",
                to="myapp.profile",
            ),
        ),
        migrations.CreateModel(
            name="AssignedReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_reviews",
                        to="myapp.example",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="myapp.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order of the question within the example"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="myapp.example",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order of the step within the question"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="myapp.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="myapp.example",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="myapp.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewQuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("completely_disagree", "Completely Disagree"),
                            ("disagree", "Disagree"),
                            ("neutral", "Neutral"),
                            ("agree", "Agree"),
                            ("completely_agree", "Completely Agree"),
                        ],
                        max_length=50,
                    ),
                ),
                ("free_response", models.TextField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="myapp.reviewquestion",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="myapp.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewStepResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sql_statement", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_responses",
                        to="myapp.question",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_responses",
                        to="myapp.review",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolnTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("solution", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                ("review_score", models.FloatField(default=0)),
                ("review", models.TextField()),
                ("is_review", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_solutions",
                        to="myapp.profile",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="myapp.problemtable",
                    ),
                ),
            ],
        ),
    ]
