# Generated by Django 5.0.6 on 2024-06-19 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_review_appropriateness_class_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("example", "reviewer")},
        ),
    ]
