# Generated by Django 5.0.6 on 2024-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_review_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solntable",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="solntable",
            name="problem",
        ),
        migrations.AlterField(
            model_name="instrchecks",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="problemtable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="QuestionStep",
        ),
        migrations.DeleteModel(
            name="SolnTable",
        ),
    ]
