# Generated by Django 5.0.6 on 2024-07-01 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_solntable_creator_remove_solntable_problem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrchecks",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="problemtable",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="reviewquestionresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="reviewquestionresponse",
            name="review",
        ),
        migrations.RenameField(
            model_name="example",
            old_name="project_context",
            new_name="problem_context",
        ),
        migrations.RenameField(
            model_name="example",
            old_name="project_description",
            new_name="problem_description",
        ),
        migrations.RenameField(
            model_name="example",
            old_name="completed",
            new_name="submitted",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="is_instructor",
            new_name="instructor",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="problem_context_like",
            new_name="constructive_suggestions",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="problem_context_suggestions",
            new_name="problem_likeness",
        ),
        migrations.AddField(
            model_name="example",
            name="instructor_reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="example",
            name="student_reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="InstrReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted", models.BooleanField(default=False)),
                ("review_score", models.FloatField(default=0)),
                ("review", models.TextField()),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instr_reviews",
                        to="myapp.example",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssignedReview",
        ),
        migrations.DeleteModel(
            name="InstrChecks",
        ),
        migrations.DeleteModel(
            name="ProblemTable",
        ),
        migrations.DeleteModel(
            name="ReviewQuestion",
        ),
        migrations.DeleteModel(
            name="ReviewQuestionResponse",
        ),
    ]
